CC      =       cc
CFLAGS	=	-g  -lm -fopenmp
RM 		= rm -f
all: CodeOpenMP 



CodeSequentiel:	CodeSequentiel.c
	$(CC) -o CodeSequentiel CodeSequentiel.c $(CFLAGS)   

clean:
	$(RM) CodeSequentiel 







